### ISSUE TITLE
Does initialize XFGloss in Android project is needed?

### ISSUE THREAD

**Issue by asafgo** [tbaggett/xfgloss#23] opened 2017-09-26 10:11 UTC
Hi,

Adding the following code to my Android project:
`// IMPORTANT: Initialize XFGloss AFTER calling LoadApplication on the Android platform
            XFGloss.Droid.Library.Init(this, savedInstanceState);`
results with error "The name 'savedInstanceState' does not exist in the current context".
When deleting this above code XFGloss works on Android project so I wander why the above line of code needed for Android project?

Thanks,
AG

**Comment by Hasanajouz** [comment] 2017-09-28 16:48
If you are just using the gradient effect for the form's  background i think it is not necessary to use this line.
It started showing the error you mentioned after updating xamarin forms to 2.4.0
I hope they update this plugin soon it's been along time since it's been updated

**Comment by ymazal** [comment] 2017-11-05 02:48
By me it does not work without it and I have the same error when I put it... 
Latest version of xf and XFGloss...
Its juste does not do anything when I don,t put this line.

**Comment by EmilAlipiev** [comment] 2017-11-07 11:41
I wonder if initialization increases start up time like any other xamarin themes. last time I used light theme, profiling showed me that it increased my start up time 2-3 secs on Android. Does it have similar effects? any experience?

**Comment by tbaggett** [comment] 2018-02-20 01:26
The new 1.1.0 version now supports NetStandard 2.0 and Xamarin.Forms 2.5. It should also resolve issues involving crashing on the Android platform during initialization. Please try the new version and let me know if it resolves your issue. Thanks!

**Comment by VirtualNomad00** [comment] 2018-02-21 11:25
The issue still exists with Xamarin.Forms 2.5 and NetStandard 2.0

**Comment by tbaggett** [comment] 2018-02-21 15:41
Thanks for trying it, @VirtualNomad00. I will test further and try to reproduce the issue.

**Comment by tbaggett** [comment] 2018-02-21 15:43
@EmilAlipiev , regarding initialization increasing start up time, all it does is basically insure that the Xamarin linker recognizes the lib is being used so it will include it in release builds.

**Comment by tbaggett** [comment] 2018-02-22 02:12
@VirtualNomad00, and everyone experiencing this issue, I reviewed the [MainActivity class](https://github.com/tbaggett/xfgloss/blob/master/src/XFGlossSample.Droid/MainActivity.cs) in the XFGlossSample.Droid project included in the repo. The savedInstanceState variable is passed as a parameter to the OnCreate method where you were supposed to add the Init statement. I've copied relevant portions of it below.

```
	public class MainActivity : Xamarin.Forms.Platform.Android.FormsAppCompatActivity
	{
		protected override void OnCreate(Bundle savedInstanceState)
		{
			Xamarin.Forms.Forms.Init(this, savedInstanceState);

			var app = new App();
			LoadApplication(app);

			XFGloss.Droid.Library.Init(this, savedInstanceState);
		}
	}
```

Can you compare this to your implementations of your Android project's MainActivity class? Please let me know how they differ. The feedback you provide may help me resolve this issue. Thanks!

**Comment by tbaggett** [comment] 2018-02-22 03:36
I've released the new v1.1.1.83 to address issue #19. Please update to it before testing this issue again, just in case they are related. Thanks!

**Comment by VirtualNomad00** [comment] 2018-02-22 07:43
@tbaggett this one is resolved .Though a suggestion you might want to  make changes in the README.md file of either changing **savedInstanceState** to **bundle** or viceversa and thanks for the quick response.
However am still facing issue #21   for both android and iOS . I have pasted my code over there

**Comment by tbaggett** [comment] 2018-02-22 14:16
@VirtualNomad00, thanks for the confirmation. I will close this issue. And thanks for pointing out the discrepancy in the README.md file. I will fix that as well. I will look into issue #21 tonight after work.

**Closed by tbaggett** 2018-02-22 14:16 UTC
Labels: bug
